name: Update NomadList Trips

#            ┌───────────── minute (0 - 59)
#            │ ┌───────────── hour (0 - 23)
#            │ │ ┌───────────── day of the month (1 - 31)
#            │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
#            │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
#            │ │ │ │ │
#            │ │ │ │ │
#            │ │ │ │ │
#            * * * * *
on:
  schedule:
    - cron: "21 2 * * *" # Every day at 2:21am
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

env:
  PR_BOT_AUTHOR: quack-bot[bot] <98925477+quack-bot[bot]@users.noreply.github.com>

jobs:
  fetch-beer-data:
    name: Fetch Beer Data
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Install Deno
        uses: denoland/setup-deno@v1

      - name: Update NomadList Trips
        id: update_nomadlist_trips
        run: deno task update-nomadlist-trips

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.BEERS_CR_PAT }}
          commit-message: |
            auto: [Beers] - New Trips Update
          committer: ${{ env.PR_BOT_AUTHOR }}
          author: ${{ env.PR_BOT_AUTHOR }}
          title: "[Beers] - Trip Schedule Updated!"
          labels: "A:Auto Merge"
          branch: "new-trips"
          branch-suffix: "short-commit-hash"
          delete-branch: true
          body: |
            Generated by `${{github.actor}}` via ${{github.sha}}
